/**
 * @file cli_config.c
 * @brief Configuration Save/Load Commands
 *
 * Follows Cisco/VyOS conventions:
 * - write / write memory / save - saves running config to startup
 * - commit - validates and saves (VyOS style)
 * - copy running-config startup-config - Cisco style
 * - show startup-config - displays saved config
 */

#include "cli.h"
#include "interface.h"
#include "nat.h"
#include "routing_table.h"
#include <arpa/inet.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <time.h>

/* The actual startup config file loaded on boot */
#define STARTUP_GATE_PATH "/etc/yesrouter/startup.gate"

/* External NAT config for saving */
extern struct nat_config g_nat_config;

/**
 * @brief Calculate prefix length from netmask
 */
static int mask_to_prefix_len(struct in_addr mask)
{
    uint32_t m = ntohl(mask.s_addr);
    int len = 0;
    while (m & 0x80000000) {
        len++;
        m <<= 1;
    }
    return len;
}

/**
 * @brief Write running config to startup.gate file
 * This file is loaded on boot via 'exec startup.gate' in yesrouter.conf
 */
static int write_startup_gate(const char *filename)
{
    FILE *fp = fopen(filename, "w");
    if (!fp) {
        printf("%% Failed to open %s for writing\n", filename);
        return -1;
    }

    time_t now = time(NULL);
    fprintf(fp, "!\n! YESRouter Startup Configuration\n");
    fprintf(fp, "! Generated: %s", ctime(&now));
    fprintf(fp, "! Do not edit this file manually - use 'write memory' or 'commit'\n");
    fprintf(fp, "!\n\n");

    /* Enter configuration mode */
    fprintf(fp, "configure terminal\n\n");

    /* Interfaces */
    for (uint32_t i = 1; i <= interface_count(); i++) {
        struct interface *iface = interface_find_by_index(i);
        if (!iface)
            continue;

        fprintf(fp, "! Interface %s\n", iface->name);
        fprintf(fp, "interface %s\n", iface->name);

        if (iface->config.ipv4_addr.s_addr) {
            char ip_buf[INET_ADDRSTRLEN];
            inet_ntop(AF_INET, &iface->config.ipv4_addr, ip_buf, sizeof(ip_buf));
            int prefix_len = mask_to_prefix_len(iface->config.ipv4_mask);
            fprintf(fp, "ip address %s/%d\n", ip_buf, prefix_len);
        }

        if (iface->config.mtu > 0 && iface->config.mtu != 1500) {
            fprintf(fp, "mtu %u\n", iface->config.mtu);
        }

        fprintf(fp, "%s\n", iface->state == IF_STATE_UP ? "no shutdown" : "shutdown");
        fprintf(fp, "exit\n\n");
    }

    /* Static routes */
    extern struct routing_table *routing_table_get_instance(void);
    struct routing_table *rt = routing_table_get_instance();
    if (rt && rt->rib_root) {
        fprintf(fp, "! Static Routes\n");

        /* Simple iterative approach - for production would need proper tree traversal */
        /* For now, just output the default route if configured */
        struct in_addr zero_net = {0};
        struct route_entry *default_route = routing_table_lookup(rt, &zero_net);
        if (default_route && default_route->source == ROUTE_SOURCE_STATIC) {
            char gw[INET_ADDRSTRLEN];
            inet_ntop(AF_INET, &default_route->next_hop, gw, sizeof(gw));
            fprintf(fp, "ip route 0.0.0.0 0.0.0.0 %s\n", gw);
        }
        fprintf(fp, "\n");
    }

    /* NAT Configuration */
    if (g_nat_config.enabled && (g_nat_config.num_pools > 0 || g_nat_config.num_rules > 0)) {
        fprintf(fp, "! NAT Configuration\n");
        fprintf(fp, "end\n\n"); /* Exit config mode first for NAT commands */

        /* NAT pools */
        for (int i = 0; i < g_nat_config.num_pools; i++) {
            struct nat_pool *pool = &g_nat_config.pools[i];
            if (pool->name[0] == '_') {
                /* Internal masquerade pool - skip, will be recreated */
                continue;
            }
            char start_ip[INET_ADDRSTRLEN], end_ip[INET_ADDRSTRLEN];
            struct in_addr start = {htonl(pool->start_ip)};
            struct in_addr end = {htonl(pool->end_ip)};
            inet_ntop(AF_INET, &start, start_ip, sizeof(start_ip));
            inet_ntop(AF_INET, &end, end_ip, sizeof(end_ip));
            fprintf(fp, "ip nat pool %s %s %s\n", pool->name, start_ip, end_ip);
        }

        /* NAT rules */
        for (int i = 0; i < g_nat_config.num_rules; i++) {
            struct nat_rule *rule = &g_nat_config.rules[i];
            if (!rule->active)
                continue;

            /* Check if this is a masquerade rule (pool name starts with _masq_) */
            if (strncmp(rule->pool_name, "_masq_", 6) == 0) {
                /* Extract interface name from pool name */
                const char *intf_name = rule->pool_name + 6;
                fprintf(fp, "ip nat inside source list %s interface %s overload\n", rule->acl_name,
                        intf_name);
            } else {
                fprintf(fp, "ip nat inside source list %s pool %s overload\n", rule->acl_name,
                        rule->pool_name);
            }
        }
        fprintf(fp, "\n");
    } else {
        fprintf(fp, "end\n\n");
    }

    fprintf(fp, "! End of configuration\n");
    fprintf(fp, "show interfaces brief\n");

    fclose(fp);
    return 0;
}

/**
 * Command: write memory / save
 */
static int cmd_write_memory(int argc, char **argv)
{
    (void)argc;
    (void)argv;

    /* Create directory if it doesn't exist */
    mkdir("/etc/yesrouter", 0755);

    printf("Building configuration...\n");
    if (write_startup_gate(STARTUP_GATE_PATH) == 0) {
        printf("[OK] Configuration saved to %s\n", STARTUP_GATE_PATH);
        return 0;
    } else {
        printf("%% Error: Failed to save configuration\n");
        return -1;
    }
}

/**
 * Command: write
 */
static int cmd_write(int argc, char **argv)
{
    if (argc >= 2 && strcmp(argv[1], "memory") == 0) {
        return cmd_write_memory(argc, argv);
    }
    /* Default: write memory */
    return cmd_write_memory(argc, argv);
}

/**
 * Command: save (alias for write memory)
 */
static int cmd_save(int argc, char **argv)
{
    (void)argc;
    (void)argv;
    return cmd_write_memory(argc, argv);
}

/**
 * Command: copy running-config startup-config
 */
static int cmd_copy(int argc, char **argv)
{
    if (argc < 3) {
        printf("Usage: copy running-config startup-config\n");
        return -1;
    }

    if (strcmp(argv[1], "running-config") == 0 && strcmp(argv[2], "startup-config") == 0) {
        return cmd_write_memory(argc, argv);
    }

    printf("%% Invalid copy command\n");
    return -1;
}

/**
 * Command: show startup-config
 */
static int cmd_show_startup_config(int argc, char **argv)
{
    (void)argc;
    (void)argv;

    FILE *fp = fopen(STARTUP_GATE_PATH, "r");
    if (!fp) {
        printf("%% Startup configuration not found at %s\n", STARTUP_GATE_PATH);
        printf("%% Use 'write memory', 'save', or 'commit' to save configuration\n");
        return -1;
    }

    char line[512];
    while (fgets(line, sizeof(line), fp)) {
        printf("%s", line);
    }

    fclose(fp);
    return 0;
}

/**
 * Command: commit
 * Saves running configuration to startup-config (Juniper/VyOS style)
 */
static int cmd_commit(int argc, char **argv)
{
    (void)argc;
    (void)argv;

    /* Create directory if it doesn't exist */
    mkdir("/etc/yesrouter", 0755);

    printf("Validating configuration...\n");
    /* Future: Add configuration validation here */

    if (write_startup_gate(STARTUP_GATE_PATH) == 0) {
        printf("Configuration committed successfully.\n");
        printf("[OK] Saved to %s\n", STARTUP_GATE_PATH);
        return 0;
    } else {
        printf("%% Error: Failed to commit configuration\n");
        printf("%% Check file permissions for %s\n", STARTUP_GATE_PATH);
        return -1;
    }
}

/**
 * Register config save/load commands
 */
void cli_register_config_commands(void)
{
    cli_register_command("write", "Write configuration to startup", cmd_write);
    cli_register_command("write memory", "Save running configuration", cmd_write_memory);
    cli_register_command("save", "Save running configuration (alias for write)", cmd_save);
    cli_register_command("commit", "Commit configuration changes (VyOS style)", cmd_commit);
    cli_register_command("copy", "Copy configuration files", cmd_copy);
    cli_register_command("show startup-config", "Display startup configuration",
                         cmd_show_startup_config);
}
